plugins {
    id 'java-library'
    id 'maven-publish'
}

base {
    archivesName = "${mod_id}-${project.name}-${minecraft_version}"
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(java_version)
    withSourcesJar()
    withJavadocJar()
}

repositories {
    mavenCentral()
    exclusiveContent {
        forRepository {
            maven {
                name = 'Sponge'
                url = 'https://repo.spongepowered.org/repository/maven-public'
            }
        }
        filter { includeGroupAndSubgroups('org.spongepowered') }
    }
    maven {
        name = "ObscuriaLocal"
        url = uri("/Users/obscuria/Modding/maven")
    }
    maven {
        name = "Obscuria"
        url = "https://raw.githubusercontent.com/ObscuriaLithium/modding/main/maven/"
    }
    maven {
        name = "CurseMaven"
        url = "https://cursemaven.com"
    }
    maven {
        // Yet Another Config Lib
        name = 'Xander Maven'
        url = 'https://maven.isxander.dev/releases'
    }
    maven {
        // Forge Config API Port
        name = "Fuzs Mod Resources"
        url = "https://raw.githubusercontent.com/Fuzss/modresources/main/maven/"
    }
    maven {
        // Mod Menu
        name = "TerraformersMC"
        url = 'https://maven.terraformersmc.com/releases/'
    }
    maven {
        // LuaJ
        url 'https://jitpack.io'
        content {
            includeGroup "com.github.FiguraMC.luaj"
        }
    }
}

dependencies {
    implementation("org.jetbrains:annotations:24.1.0")
    implementation("com.google.code.findbugs:jsr305:3.0.1")
    compileOnly("org.checkerframework:checker-qual:3.43.0")
    annotationProcessor("org.checkerframework:checker:3.43.0")
    compileOnly "org.projectlombok:lombok:1.18.40"
    annotationProcessor "org.projectlombok:lombok:1.18.40"
}

sourcesJar {
    from(rootProject.file('LICENSE.md'))
}

jar {
    from(rootProject.file('LICENSE.md'))

    manifest {
        attributes([
                'Specification-Title'   : mod_name,
                'Specification-Vendor'  : mod_author,
                'Specification-Version' : project.jar.archiveVersion,
                'Implementation-Title'  : project.name,
                'Implementation-Version': project.jar.archiveVersion,
                'Implementation-Vendor' : mod_author,
                'Built-On-Minecraft'    : minecraft_version
        ])
    }
}

processResources {
    var expandProps = [
            'version'                      : version,
            'group'                        : project.group,
            'minecraft_version'            : minecraft_version,
            'minecraft_version_range'      : minecraft_version_range,
            'fabric_version'               : fabric_version,
            'fabric_loader_version'        : fabric_loader_version,
            'mod_name'                     : mod_name,
            'mod_author'                   : mod_author,
            'mod_id'                       : mod_id,
            'license'                      : license,
            'description'                  : project.description,
            'neoforge_version'             : neoforge_version,
            'neoforge_loader_version_range': neoforge_loader_version_range,
            'credits'                      : credits,
            'java_version'                 : java_version,
            'fragmentum_version'           : fragmentum_version,
            'curseforge_fabric'            : curseforge_fabric,
            'curseforge_neoforge'          : curseforge_neoforge,
            'modrinth'                     : modrinth,
            'sources'                      : sources,
            'issues'                       : issues,
            'discord'                      : discord,
            'update_lookup'                : update_lookup
    ]

    var jsonExpandProps = expandProps.collectEntries {
        key, value -> [(key): value instanceof String ? value.replace("\n", "\\\\n") : value]
    }

    filesMatching(['META-INF/mods.toml', 'META-INF/neoforge.mods.toml']) {
        expand expandProps
    }

    filesMatching(['pack.mcmeta', 'fabric.mod.json', '*.mixins.json']) {
        expand jsonExpandProps
    }

    inputs.properties(expandProps)
}

publishing {
    publications {
        register("api", MavenPublication) {
            groupId = "dev.obscuria"
            artifactId = "fragmentum-${project.name}"
            version = "${minecraft_version}-${version}"
            artifact(tasks.jar) {
                classifier = null
            }
        }
    }
    repositories {
        maven {
            name = 'ObscuriaMaven'
            url = uri('/Users/obscuria/Modding/maven')
        }
    }
}