modLoader = "javafml"
loaderVersion = "[41,)"
license = "Obscuria Lithium (c) 2022, All Rights Reserved"
[[mods]]
modId = "loot_journal"
version = "1.1.0"
displayName = "Loot Journal"
logoFile = "none.png"
credits = "Everyone who supports me on Patreon!"
authors = "Obscuria"
description = '''
Loot Journal adds a log of the
items you have picked up and
counts the total number of
similar items in your inventory
'''

[[dependencies.loot_journal]]
modId = "forge"
mandatory = true
versionRange = "[41,)"
ordering = "NONE"
side = "BOTH"