modLoader = "javafml"
loaderVersion = "[43,)"
license = "Obscuria Lithium (c) 2022, All Rights Reserved"

[[mods]]
    modId = "loot_journal"
    version = "2"
    displayName = "Loot Journal"
    logoFile = "none.png"
    credits = "Everyone who supports me on Patreon!"
    authors = "Obscuria"
    displayTest = "IGNORE_ALL_VERSION"
    description = '''
    Loot Journal adds a log of the
    items you have picked up and
    counts the total number of
    similar items in your inventory
    '''

[[dependencies.loot_journal]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.19.2,)"
    ordering = "NONE"
    side = "CLIENT"

[[dependencies.loot_journal]]
    modId = "forge"
    mandatory = true
    versionRange = "[43.2.0,)"
    ordering = "NONE"
    side = "CLIENT"