modLoader = "javafml"
loaderVersion = "[43,)"
license = "Obscuria Lithium (c) 2024, All Rights Reserved."

[[mods]]
    modId = "loot_journal"
    version = "3"
    displayName = "Loot Journal"
    credits = "Everyone who supports me on Patreon!"
    authors = "Obscuria"
    displayTest = "IGNORE_ALL_VERSION"
    description = '''
    Loot journal displays notifications about
    picking up items and counts the total number
    of the same items in the inventory.
    '''

[[dependencies.loot_journal]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.19.2,)"
    ordering = "NONE"
    side = "CLIENT"

[[dependencies.loot_journal]]
    modId = "forge"
    mandatory = true
    versionRange = "[43.3.0,)"
    ordering = "NONE"
    side = "CLIENT"